Vagrant.configure("2") do |config|
    config.vm.define "Jenkins" do |web01|
      web01.vm.box = "bento/ubuntu-22.04"
      web01.vm.hostname = "Jenkins"
      web01.vm.network "private_network", ip: "192.168.56.41"
    end
 end
  